name: Kiểm thử 
on: 
push: true
paths:
  'README.md'
  '!docs/**'
  '!**js'

branches: [main]
jobs: 
kiemthu-job:
run-on: windows-11
steps:
-uses: actions/checkout@v3
name: checkout code from GitHub
-run: npm install
name: install npm package
-run: node pheptoan.js
name: run node pheptoanlicaction


