name: kiemthu
on:
  push:
    paths:
      - 'README.md'
      - '!docs/**'
      - '**js'
    branches: [main]
jobs:
  kiemthu-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from GitHub
        uses: actions/checkout@v3
      - name: install npm package
        run: npm install
      - name: run node pheptoanlicaction
        run: node pheptoan.js 
